{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "زمان پاسخ به درخواست های دیتابیس",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "response_time", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "تعداد خطاهای دیتابیس",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "num_db_errors_total", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "زمان پاسخ به درخواست های وضعیت deployment",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "response_time", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "تعداد درخواست ها",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "num_requests_total", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "تعداد درخواست ها با نتیجه ناموفق",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    { "expr": "num_failed_requests_total", "legendFormat": "{{path}}" }
   ]
  }
 ]
}