apiVersion: v2
name: kaas-api
description: A Helm chart for Kubernetes-as-a-Service API
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 15.5.12
    repository: https://charts.bitnami.com/bitnami
