replicas: 1
image:
  repository: mohammadh915/kaas-api
  tag: 1.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: kaas-api.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5
#kubeconfig:
#  enabled: true
#  config: |
#    apiVersion: v1
#    clusters:
#    - cluster:
#        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJME1EUXhPREUyTXpZd05Gb1hEVE0wTURReE56RTJNell3TkZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS05NCkhtRTVHcWR1NTJRcDl5WlphaUQyVHRFbXNBQkpVakJ5M0hycDJnMU5NYzJTb0FZWE5FSys1TTN1bytBWGJFQ1oKSGkvTjFMSlpZOS9oUlkrbnU2WGZzWEVQYW9CNVNrQXVrUE43Mk5KY2EwTG1iREU0K2xHcUNqSFllWlFPU1pzVApiblNYdytNVFNPTEdtalNUUXV3TVJta3RlRDdCYzRMSFNnYTZLd1p2aVgzbzZvaGd1RCs2eHlrM2dvVDQ3dElJCldVcGlhRWVPYmlDdGNmTDdVZE1WTjNpQUExbktIb0EzOGVwbEZtaEh5TVQ3ZjZraEVFakkxMDRLa01lVmsrNFgKOGNYaGZJODRSa1pFamhhM2EvWml1WVJzNFJzR09mY3lDdHo5a1A1OFpHQjNscWFkQUJHREU4b3lUaVRTZTlwbgpWdGQwYVhwRnVXbkFPYkxaT3VFQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJTT2wrenMvbXRQcm5WOUtMbFlkcy9kdkdtdDJqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFleHAxU2JJUgpsQUE3My93cFNNY2lhazhUTGlmZXpVNVhvYytSZHVNbTlLL2F6eWMxRitKbUVLa2JrWXVOWUxWY3hFbTBDblhWCmVXOWFDdlhic1RHYmtWemtDWjgwZGxGVDJSSXZJTkFwYkN5T2NZbXdEK1MveHpGdU81SUlMTkdxZHUxTXoxSlcKVmsvR1h5SVVWbUtHb05GcWsxYTF1OFRQMklwTW1xcGY4U1ZzYkxJUWl1ZDZBZHY5VWRhYWIwdnQzQTNrdDlGNAowdEQvVkVac3d4NHBxOEtQeDNZNFhyc21sckJoWFoyc2l0MWc0VWJRSHZlMnY0bHFhN001QnlpSmQ0cHJyNmF5CjNWTWh6TXZQT1ZINjduQ05oNHBaNTBLU1lLYVVaWDR5dnZmRlpNU1ZsbHBtNDVUVlZTNmVtL1ljcjZ2ZERnejMKS3hiaG8rZTU0MmxkT3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
#        server: https://127.0.0.1:50058
#      name: minikube
#    contexts:
#    - context:
#        cluster: minikube
#        namespace: default
#        user: minikube
#      name: minikube
#    current-context: minikube
#    kind: Config
#    preferences: {}
#    users:
#    - name: minikube
#      user:
#        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJME1EY3dNVEV3TWprek0xb1hEVEkzTURjd01qRXdNamt6TTFvd01URVhNQlVHQTFVRQpDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGakFVQmdOVkJBTVREVzFwYm1scmRXSmxMWFZ6WlhJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDMG96K3ZWcXV1RFJhakxEbEplMFVIS2s1TGdTSDEKakhIQlNvZEl2d25kOEx3ckZoM3JFMnVXZHZ3YXo4L2xwZHlTYURFV1YxbURqWG1DaFc3UGowZ2FHOXhsczZkbwo0V3RzVGl2UzJLaG9zbWxKbk12TG1jY1p3QjNPTUFMN3NDNG9laEJUOGh6L3ZoSHg3UjhFZ0dtMHROUURFQ092CldWVzhHK1JzT1d1VUJXbUM2bUp5eDlMclVTM1pISlhhZU4rL3B0Q1J5SVppYXNodUVFb2NJcmFnaWVVRXBnejQKelJOcGxDeEc4d2tnb2RFMVI5dk12Zm4yY09kenEvc0c2d2ZjeE9IN0k1cit5MGw2d2U1MmR4VmJ3cHZjUGVoaApJQVh4Nm5XUnordUhYZnhwbWRqWUtsaXVQcmhKaE1hVk05ZmFMTjdtczVlOVVEUjM2L3JBWnkxTEFnTUJBQUdqCllEQmVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JTT2wrenMvbXRQcm5WOUtMbFlkcy9kdkdtdAoyakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZ2t2cHZ0TkhrZ1lMRWZiUURzMDl5VG9kd3Nic1hQRWU5NmxRCk9reDNFcWVOZjJXSm5XZlh2MTdQNnA5RzZNRXdJN2hrVTZSTlMxUXRZWHA1Sy9NNFoweEw4SkFsWjFRQURFSHUKd045QWZsZzNnVk1qaFNxOXdpS2luRVQ3WGlCeWZIWnd1dXhJZ3N4YlROY2JRc2ZKZjBPeFBBbkFERHVCVVNocQptK0hINWpKMXFmNmRUclh5MG5HT3oyc3JKdW5mZVM5UjFOT1J2UFRnWnpkMFdNYzZaOEYwaVN2RmJjUEpJYno2Cldmd2xnaGVGbTJwNVRVRmJwQXFGc296RFRpR3g0bDIyeGdmME5WdllKVjcrMnFxQUxMUU4vYzBRUXkvQXQyemQKZVFYWEhaQU9EU2F4SjNxZDRrZkc2UUJOQlpKNURXMHU4OHJ5T1lmRXdLVjFja3UyUnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
#        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdEtNL3IxYXJyZzBXb3l3NVNYdEZCeXBPUzRFaDlZeHh3VXFIU0w4SjNmQzhLeFlkCjZ4TnJsbmI4R3MvUDVhWGNrbWd4RmxkWmc0MTVnb1Z1ejQ5SUdodmNaYk9uYU9GcmJFNHIwdGlvYUxKcFNaekwKeTVuSEdjQWR6akFDKzdBdUtIb1FVL0ljLzc0UjhlMGZCSUJwdExUVUF4QWpyMWxWdkJ2a2JEbHJsQVZwZ3VwaQpjc2ZTNjFFdDJSeVYybmpmdjZiUWtjaUdZbXJJYmhCS0hDSzJvSW5sQktZTStNMFRhWlFzUnZNSklLSFJOVWZiCnpMMzU5bkRuYzZ2N0J1c0gzTVRoK3lPYS9zdEplc0h1ZG5jVlc4S2IzRDNvWVNBRjhlcDFrYy9yaDEzOGFablkKMkNwWXJqNjRTWVRHbFRQWDJpemU1ck9YdlZBMGQrdjZ3R2N0U3dJREFRQUJBb0lCQUdyb1R6R3pwdW5jM3kvMQpaWFpDMllpekZpR0RySmlKNVcxVGNadXhUT0tvcm9VRmt2Rmt6Z0VBTEphbHRWSWlCdGd6aUJIRDRydUVDSTBoCjhZSXdONmtVSWkyaTFRcXlsd1JEZzVaSEdlelU0cEZwbGdmSzNGWTJLSzIySnAzVkdJeG1LYkcxRWtxZHNEc3gKYm5FWW12Y1RLb01oa3kwZFB5dVVpbTB1MHFlSVNITkROT2luUmw0MkxTKzdtS1M2VytZQ3I1V1diN3JYVmhOcApCdHVOM1RaWUZIUFl5MmZJMnZ5U3BqUytvS1RaNVVvYXJyRnZoMXQrY1pqWUZ2eXE2ejZNWGJxOWUxZnpZY2FJCnJyWVZ2TzA5QWMySmY2N1NqOWxOSG9HL1dQb1J3QzhPZUJPdGxJQjdxQTBIdGlVY2tBaTJGWk5CQVRZNWhZZ0UKdzU5Ky9ta0NnWUVBd1JLZUtSVVd5aXoxc3Y1RjFTOGVBb0daUGlTY0xMSU14bW5UL2lFNjlmMDJrYWVCN1ByNworejZXU3dFdU43empkaUZldm85YXg5T1UzZmFSS3ZpbHo0N2ppNDBQYXNzcDNnU3JlSitML2dtcVkzTDVWWi9UCnFkL01DYXBYODVvdkRLb2xkZ1Ryak1Ld2lXUjNVd3F3Rlo3dDNLMmI5ZUdtbG1NalhTemJCYVVDZ1lFQTc0TVgKTkRaU0NBM1FIWGhNMGZrSjV4U3Q3cEFQdmtLYk5pd3ZnUUlxMHlNSHBLQVhaZkZRZXBMR1hoazdhNGh2MVRhcQp6QVIvMUNMK0tuUmNralVVYzdjMjd1RXFEZFQwQmI4MjRPMnhSaEhYdENDZU53enIwa2wyRjdHWll3ZnR6NmpDClRuZ20vUmRCQXIzbTZ5TVBMRGIrcm9ZM3crdC9ncG5vSHROTFZDOENnWUFhZlpOMXo0N3c3bnBIdE51Z0JIYjUKb1E2Rm1FQlZZWmlmSUtZVm1EbWV4cjlWL01XMjNqajBvQUcvQ01wdW0xd2FPVG5tcTRTcEpqNm10YzMxTjJpSQpzZkpHazNRcUV2WUxvRmhtbEgyQXZaTERVbU1qZkdwdVJHYWFiT1RrWjZOTStZdHFSZ0tMcmFyTEx4MndKeWRCCjBDeVN1cjlMWFVxZUY3d2liS1VnZ1FLQmdFVWE0SzRLNGo0NnBncHF0RmQ4OEZPQkR2SWZGTHZEZ2Y3dVhzSnQKT3FmeW1uandTKy80NFV5TVhybTF0QVJCdUdxZlBFWmpJZksyS2ZsYjIzMi8zT2ZLUEFwT1l4RGNtWSt5N1FXVwo3eWdWYTlRbitSNVBGeGQwWktOUGRiOHlBWGFCN1pZd2FxZHBkek53VVZrVW80TVJWd2hKNTNzYXpvNkRFNHNaClVjbTNBb0dCQUlJYXBTNEVoQmVTdXdudlJraXpxY003VEMyM25aRVBFcTRPTUdORENkNFZjdFVPZmozLzBCWTMKUzRtWE9kNlRSN09XRTdDRFVoRERCemoyRG5FeGl0QlV0bGZ5TUNHNWJDV1NsR09CWUViTitLQ3NzS3hraEdPdgpocm1id1ZlTHZ1WU9FU09nUGI0YnpUbE1ySnozSEZtYXpnRGZ6Qk1ETDJKOEY0NVYwZ2plCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==


