apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kaas-api.fullname" . }}
  labels:
    {{- include "kaas-api.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kaas-api.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
