apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: "{{ .Values.postgresqlMaster.name }}.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "mydatabase"
  DB_USER: "myuser"
  DB_PASSWORD: "mypassword"
  DB_HOST_SLAVE: "{{ .Values.postgresqlSlave.name }}.default.svc.cluster.local"